security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

            anonymous: ~
            form_login:
                login_path: login
                check_path: login
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
           # require ROLE_ADMIN for /admin*
           - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
           #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
           #- { path: ^/, roles: ROLE_USER }
           #- { path: ^/, roles: ROLE_ADMIN }
