security:
    encoders:
        App\Entity\User:
            algorithm: plaintext

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username

                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:

        main:
#TODO: add ^\user as pattern
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

        dev:
            # //exclude WDTrequests
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
           # require ROLE_ADMIN for /admin*
           - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
           - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
           - { path: ^/, roles: ROLE_USER } # fix to /* when done
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html