#framework:
#    default_locale: '%locale%'
 #   translator:
  #      paths:
   #         - '%kernel.project_dir%/translations'
    #    fallbacks:
     #       - '%locale%'
framework:
    default_locale: 'en'
    translator:
        fallbacks: ['en']